<?php
/**
 * Colors extracted from SCSS local-colors variable defined in /src/scss/variables.scss
 * Do not edit this file, define colors in scss.
 */

return array(
	array(
		'name'  => 'Accent variant',
		'slug'  => 'accent-variant',
		'color' => '#1A78B6',
	),
	array(
		'name'  => 'Accent',
		'slug'  => 'accent',
		'color' => '#0F95B7',
	),
	array(
		'name'  => 'Gold',
		'slug'  => 'gold',
		'color' => '#ffd000',
	),
	array(
		'name'  => 'Semantic warning',
		'slug'  => 'semantic-warning',
		'color' => '#faa614',
	),
	array(
		'name'  => 'Semantic error',
		'slug'  => 'semantic-error',
		'color' => '#b00020',
	),
	array(
		'name'  => 'Semantic success',
		'slug'  => 'semantic-success',
		'color' => '#008738',
	),
	array(
		'name'  => 'Semantic info',
		'slug'  => 'semantic-info',
		'color' => '#006bb2',
	),
	array(
		'name'  => 'White',
		'slug'  => 'white',
		'color' => '#fff',
	),
	array(
		'name'  => 'Light',
		'slug'  => 'light',
		'color' => '#f0f0f0',
	),
	array(
		'name'  => 'Black',
		'slug'  => 'black',
		'color' => '#000',
	),
	array(
		'name'  => 'Dark',
		'slug'  => 'dark',
		'color' => '#242424',
	),
	array(
		'name'  => 'Dark gray',
		'slug'  => 'dark-gray',
		'color' => '#212121',
	),
	array(
		'name'  => 'Light gray',
		'slug'  => 'light-gray',
		'color' => '#f1f1f1',
	),
	array(
		'name'  => 'Middle gray',
		'slug'  => 'middle-gray',
		'color' => '#6b6b6b',
	),
	array(
		'name'  => 'Gray',
		'slug'  => 'gray',
		'color' => '#5b5b5b',
	),
);
